### PR TITLE
change baselayout

### PR DESCRIPTION
**Pull request by walkerta**
change library from MUI to http://www.material-ui.com/#/ and fixed baselayout

### CODE REVIEW

**Comment by arscholtes** [comment]
I went ahead and merged that, it was saying there were no conflicts.

**Comment by walkerta** [comment]
Cool going to work ahead I didn't like MUI.

**Comment by arscholtes** [comment]
Oh were you not planning to do that?

**Comment by walkerta** [comment]
Edwin suggested Materials MUI so I am going to try that.

**Pull request merged**
